/* generated by Svelte v3.32.3 */
import { SvelteComponent, init, safe_not_equal } from '/spa/web_modules/svelte/internal/index.mjs';

const sortByDate = (items, order) => {
	items.sort((a, b) => {
		// Must have field named "date" in content source to work.
		let dateA = new Date(a?.fields?.date);

		let dateB = new Date(b?.fields?.date);
		return order == "oldest" ? dateA - dateB : dateB - dateA;
	});

	return items;
};

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, null, safe_not_equal, {});
	}
}

export default Component;
export { sortByDate };