/* generated by Svelte v3.32.3 */
import {
	SvelteComponent,
	append,
	attr,
	children,
	claim_element,
	claim_space,
	claim_text,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space,
	text
} from '/spa/web_modules/svelte/internal/index.mjs';

function create_fragment(ctx) {
	let ul;
	let li0;
	let t0;
	let sup0;
	let t1;
	let t2;
	let li1;
	let t3;
	let sup1;
	let t4;

	return {
		c() {
			ul = element("ul");
			li0 = element("li");
			t0 = text("specialty");
			sup0 = element("sup");
			t1 = text("2");
			t2 = space();
			li1 = element("li");
			t3 = text("imported");
			sup1 = element("sup");
			t4 = text("3");
			this.h();
		},
		l(nodes) {
			ul = claim_element(nodes, "UL", { class: true });
			var ul_nodes = children(ul);
			li0 = claim_element(ul_nodes, "LI", { class: true });
			var li0_nodes = children(li0);
			t0 = claim_text(li0_nodes, "specialty");
			sup0 = claim_element(li0_nodes, "SUP", { class: true });
			var sup0_nodes = children(sup0);
			t1 = claim_text(sup0_nodes, "2");
			sup0_nodes.forEach(detach);
			li0_nodes.forEach(detach);
			t2 = claim_space(ul_nodes);
			li1 = claim_element(ul_nodes, "LI", { class: true });
			var li1_nodes = children(li1);
			t3 = claim_text(li1_nodes, "imported");
			sup1 = claim_element(li1_nodes, "SUP", { class: true });
			var sup1_nodes = children(sup1);
			t4 = claim_text(sup1_nodes, "3");
			sup1_nodes.forEach(detach);
			li1_nodes.forEach(detach);
			ul_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(sup0, "class", "svelte-uy6qib");
			attr(li0, "class", "svelte-uy6qib");
			attr(sup1, "class", "svelte-uy6qib");
			attr(li1, "class", "svelte-uy6qib");
			attr(ul, "class", "svelte-uy6qib");
		},
		m(target, anchor) {
			insert(target, ul, anchor);
			append(ul, li0);
			append(li0, t0);
			append(li0, sup0);
			append(sup0, t1);
			append(ul, t2);
			append(ul, li1);
			append(li1, t3);
			append(li1, sup1);
			append(sup1, t4);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(ul);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;