/* generated by Svelte v3.32.3 */
import {
	SvelteComponent,
	append,
	attr,
	children,
	claim_element,
	claim_space,
	claim_text,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	set_data,
	space,
	text
} from '/spa/web_modules/svelte/internal/index.mjs';

function create_fragment(ctx) {
	let article;
	let header;
	let h2;
	let t0;
	let t1;
	let section;
	let p;
	let t2;
	let t3;
	let footer;
	let span;
	let t4;
	let t5;
	let t6;
	let t7;
	let t8;
	let t9;
	let a;

	return {
		c() {
			article = element("article");
			header = element("header");
			h2 = element("h2");
			t0 = text(/*title*/ ctx[0]);
			t1 = space();
			section = element("section");
			p = element("p");
			t2 = text(/*body*/ ctx[1]);
			t3 = space();
			footer = element("footer");
			span = element("span");
			t4 = text(/*date*/ ctx[2]);
			t5 = text(" · ");
			t6 = text(/*readTime*/ ctx[3]);
			t7 = text(" · ");
			t8 = text(/*author*/ ctx[4]);
			t9 = space();
			a = element("a");
			this.h();
		},
		l(nodes) {
			article = claim_element(nodes, "ARTICLE", { class: true });
			var article_nodes = children(article);
			header = claim_element(article_nodes, "HEADER", { class: true });
			var header_nodes = children(header);
			h2 = claim_element(header_nodes, "H2", { class: true });
			var h2_nodes = children(h2);
			t0 = claim_text(h2_nodes, /*title*/ ctx[0]);
			h2_nodes.forEach(detach);
			header_nodes.forEach(detach);
			t1 = claim_space(article_nodes);
			section = claim_element(article_nodes, "SECTION", { class: true });
			var section_nodes = children(section);
			p = claim_element(section_nodes, "P", { class: true });
			var p_nodes = children(p);
			t2 = claim_text(p_nodes, /*body*/ ctx[1]);
			p_nodes.forEach(detach);
			section_nodes.forEach(detach);
			t3 = claim_space(article_nodes);
			footer = claim_element(article_nodes, "FOOTER", { class: true });
			var footer_nodes = children(footer);
			span = claim_element(footer_nodes, "SPAN", {});
			var span_nodes = children(span);
			t4 = claim_text(span_nodes, /*date*/ ctx[2]);
			t5 = claim_text(span_nodes, " · ");
			t6 = claim_text(span_nodes, /*readTime*/ ctx[3]);
			t7 = claim_text(span_nodes, " · ");
			t8 = claim_text(span_nodes, /*author*/ ctx[4]);
			span_nodes.forEach(detach);
			footer_nodes.forEach(detach);
			t9 = claim_space(article_nodes);

			a = claim_element(article_nodes, "A", {
				class: true,
				"aria-label": true,
				href: true
			});

			children(a).forEach(detach);
			article_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(h2, "class", "svelte-qyda2w");
			attr(header, "class", "entry-header");
			attr(p, "class", "svelte-qyda2w");
			attr(section, "class", "entry-content");
			attr(footer, "class", "byLine svelte-qyda2w");
			attr(a, "class", "entry-link");
			attr(a, "aria-label", "post link to Installation | Update");
			attr(a, "href", "https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/");
			attr(article, "class", "post-entry svelte-qyda2w");
		},
		m(target, anchor) {
			insert(target, article, anchor);
			append(article, header);
			append(header, h2);
			append(h2, t0);
			append(article, t1);
			append(article, section);
			append(section, p);
			append(p, t2);
			append(article, t3);
			append(article, footer);
			append(footer, span);
			append(span, t4);
			append(span, t5);
			append(span, t6);
			append(span, t7);
			append(span, t8);
			append(article, t9);
			append(article, a);
		},
		p(ctx, [dirty]) {
			if (dirty & /*title*/ 1) set_data(t0, /*title*/ ctx[0]);
			if (dirty & /*body*/ 2) set_data(t2, /*body*/ ctx[1]);
			if (dirty & /*date*/ 4) set_data(t4, /*date*/ ctx[2]);
			if (dirty & /*readTime*/ 8) set_data(t6, /*readTime*/ ctx[3]);
			if (dirty & /*author*/ 16) set_data(t8, /*author*/ ctx[4]);
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(article);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { title } = $$props,
		{ body } = $$props,
		{ date } = $$props,
		{ readTime } = $$props,
		{ author } = $$props;

	$$self.$$set = $$props => {
		if ("title" in $$props) $$invalidate(0, title = $$props.title);
		if ("body" in $$props) $$invalidate(1, body = $$props.body);
		if ("date" in $$props) $$invalidate(2, date = $$props.date);
		if ("readTime" in $$props) $$invalidate(3, readTime = $$props.readTime);
		if ("author" in $$props) $$invalidate(4, author = $$props.author);
	};

	return [title, body, date, readTime, author];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			title: 0,
			body: 1,
			date: 2,
			readTime: 3,
			author: 4
		});
	}
}

export default Component;